AWSTemplateFormatVersion: "2010-09-09"  
Description: "Template to spin up EC2 server"
Resources:  
  MyEc2Server:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04d5cc9b88f9d1d39
      KeyName: yp-test
      SecurityGroupIds:
        - sg-0518735c186e87a70
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId: subnet-045f773dd295ba4ea
      Tags:
        - Key: "Name"
          Value: "CF-EC2-Bas"
        - Key: "Environment"
          Value: "Dev"
      UserData:
        Fn::Base64:
          !Sub: |
            # !/bin/bash -xe
            yum update -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -s ${AWS::StackId} -r MyEc2Server --region ${AWS::Region} || error_exit 'Failed to run cfn-init'

    Metadata:
      Comment: Install java and download our artifact from S3
      AWS::Cloudformation::Init:
        config:
          packages:
            yum:
              java-1.8.0: []
          commands:
            copyFromS3:
              command: "aws s3 cp s3://jworks-yp-releases/bas-petclinic.jar /app.jar"
            runApp:
              command: "java -jar /app.jar"