AWSTemplateFormatVersion: "2010-09-09"  
Description: "Template to spin up EC2 server"
Resources:  
  MyEc2Server:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0ec1ba09723e5bfac
      KeyName: yp-central-kp
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId: subnet-a37495ca
          GroupSet:
            - !Ref MySecurityGroup
      IamInstanceProfile: "YPDeployRole"
      Tags:
        - Key: "Name"
          Value: "CF-EC2-Bas"
        - Key: "Environment"
          Value: "Dev"
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -ex
          # run some commands
          yum update -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -s ${AWS::StackId} -r MyEc2Server --region ${AWS::Region} || error_exit 'Failed to run cfn-init'
          /opt/aws/bin/cfn-signal --exit-code 0 --resource MyEc2Server --region ${AWS::Region} --stack ${AWS::StackName}
    Metadata:
      Comment: Install java and download our artifact from S3
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              java-1.8.0-openjdk-devel: []
          commands:
            copyFromS3:
              command: "aws s3 cp s3://jworks-yp-releases/bas-petclinic.jar /app.jar"
            runApp:
              command: "java -jar /app.jar"
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "My sg from cloudformation"
      GroupName: "cf-bas-sg"
      VpcId: vpc-c51cfaac
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
Outputs:
  MyEc2Url:
    Description: "Public URL of the EC2 server created"
    Value: !GetAtt MyEc2Server.PublicDnsName